version: '3.8'

volumes:
  postgres_data:

services:
  fastapi:
    image: test_app:latest
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8080:80"
    depends_on:
      - db
      - redis
      - celery

  celery:
    image: test_app:latest
    command: celery -A app.tasks.celery_app worker --loglevel=info
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_KEY=${API_KEY}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data